// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  article_slice: dynamic(() => import("./ArticleSlice")),
  rich_text: dynamic(() => import("./RichText")),
};
